### ISSUE TITLE
プリンターにBluetooth接続できない

### ISSUE THREAD

**Issue by Vetteru** [star-micronics/react-native-star-io10#1]
- StarIO SDKでスキャンした際は、Bluetoothだと検出されないがBluetooth Low Energyだと検出された。
- プリンターを検出するサンプル( https://github.com/star-micronics/react-native-star-io10/blob/master/example/samples/discovery/App.tsx )を動かしたが、検出出来なかった。
- このライブラリのInterfaceTypeにBluetoothはあるが、Bluetooth Low Energyは無くて問題ないのか。

ご確認お願いします 🙇‍♂️

**Comment by bandit-ibayashi** [comment]
@Vetteru,
今後のアップデートにて、iOSでのBluetooth Low Energy対応を予定しております。よろしくお願いいたします。

**Comment by Vetteru** [comment]
@bandit-ibayashi ご回答ありがとうございました。

**Comment by bandit-ibayashi** [comment]
@Vetteru 大変お待たせいたしましたが、V1.0にてiOSでのBluetooth Low Energyに対応いたしました。SM-L200およびSM-L300にてご利用いただけます。
