### ISSUE TITLE
The sdk fails to discover printers over usb

### ISSUE THREAD

**Issue by Brettm12345** [star-micronics/react-native-star-io10#100]
## Description
A clear and concise description of what a bug is.

## Your device where the bug occurs 
 - Device: 
    Ipad

## Your printer
- Model Names:
    mC-Print3
- Firmware Version:
    3.5
- Interface:
    usb

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

Also, the result of executing the command `npx react-native info`.

I have the following code to discover a printer over usb
```typescript
import constate from 'constate';
import {useState, useCallback, useEffect} from 'react';
import {
  StarDeviceDiscoveryManager,
  StarDeviceDiscoveryManagerFactory,
  InterfaceType,
  StarPrinter,
} from 'react-native-star-io10';

const usePrinterState = () => {
  const [printer, setPrinter] = useState<StarPrinter>();
  const [discovering, setDiscovering] = useState(false);
  const [manager, setManger] = useState<StarDeviceDiscoveryManager>();
  const setupManger = useCallback(async () => {
    setManger(
      await StarDeviceDiscoveryManagerFactory.create([InterfaceType.Usb]),
    );
    manager.discoveryTime = 10000;
    manager.onDiscoveryFinished = () => {
      setDiscovering(false);
    };
    manager.onPrinterFound = printer => {
      setPrinter(printer);
      setDiscovering(false);
    };
  }, [setManger]);
  const discover = async () => {
    setDiscovering(true);
    await manager?.startDiscovery();
  };
  useEffect(() => {
    setupManger();
  }, []);
  return {
    discovering,
    discover,
    printer,
  };
};

export const [PrinterContext, usePrinter] = constate(usePrinterState);
```
The manager never stops discovering. Is there something I'm doing wrong?

**Comment by Tatsuki-Yamamoto2731** [comment]
@Brettm12345 
Did you set "Supported external accessory protocols"?

If you don't, please do the below action.
https://github.com/star-micronics/react-native-star-io10/tree/master#1-set-supported-external-accessory-protocols

**Comment by gare-bear** [comment]
@Brettm12345 I'm closing this issue since there's been no response for sometime now. We can reopen this issue if you still need help.
