### ISSUE TITLE
Could not resolve all artifacts for configuration ':react-native-star-io10:classpath'.

### ISSUE THREAD

**Issue by Frankiz123** [star-micronics/react-native-star-io10#101]
## Description

A problem occurred configuring project ':react-native-star-io10'.
> Could not resolve all artifacts for configuration ':react-native-star-io10:classpath'.
   > Could not find com.facebook.react:react-native-gradle-plugin:.
     Required by:
         project :react-native-star-io10

my react native version is  "react-native": "0.67.2",

## Your device where the bug occurs 
 it occur on the android when I try to run app on android studio it appears
<img width="1280" alt="Screenshot 2023-06-19 at 2 14 32 AM" src="https://github.com/star-micronics/react-native-star-io10/assets/17431855/1b3a6132-0ba7-4efd-a8f5-21efa28c1305">

**Comment by tuan2603** [comment]
I'm sample
![image](https://github.com/star-micronics/react-native-star-io10/assets/17542202/e07f05dd-b64a-4404-ad6d-bacb8b76164e)
"react": "17.0.2",
"react-native": "0.67.5"
"react-native-star-io10": "^1.2.0",

**Comment by gare-bear** [comment]
@Frankiz123 please update your post to include all of the information we require in our bug or question template.

**Comment by 592da** [comment]
also reproducing with
    "react-native-star-io10": "^1.3.0",
    "react-native": "^0.72.1",
    "react": "18.2.0",

cannot assemble build for release

```
* What went wrong:
Execution failed for task ':react-native-star-io10:bundleReleaseLocalLintAar'.
> Error while evaluating property 'hasLocalAarDeps' of task ':react-native-star-io10:bundleReleaseLocalLintAar'.
   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-star-io10 project caused this error: /../node_modules/react-native-star-io10/android/src/lib/stario10.aar
   ```

**Comment by can-miki** [comment]
@Frankiz123 @tuan2603 
We deeply regret for the delay in contacting you.
Then what happened to the problem?
Does the same issue occur with the current latest StarXpand SDK (v1.6.1)?

If the problem persists, we would appreciate it if you would update your submission to include all the necessary information in the bug/question template.
