### ISSUE TITLE
Task :react-native-star-io10:bundleReleaseLocalLintAar FAILED

### ISSUE THREAD

**Issue by aviksingh04** [star-micronics/react-native-star-io10#106]
## Description
I'm using r"eact-native-star-io10":"1.5.0". it is working fine for debug build. but when I'm trying to build release build it an error.  heree it is: 

> Task :react-native-star-io10:bundleReleaseLocalLintAar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-star-io10:bundleReleaseLocalLintAar'.
> Error while evaluating property 'hasLocalAarDeps' of task ':react-native-star-io10:bundleReleaseLocalLintAar'.
   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-star-io10 project caused this error: /pathofMyProject/node_modules/react-native-star-io10/android/src/lib/stario10.aar

## Project config:
  -  "react-native-star-io10": "^1.5.0",
  -  "react": "^18.2.0",
   - "react-native": "0.72.7",

**Comment by gare-bear** [comment]
@aviksingh04 have you tried [this](https://github.com/star-micronics/react-native-star-io10/issues/29#issuecomment-949719776) already?

**Comment by can-miki** [comment]
This issue will be closed because it is a duplicate.
