### ISSUE TITLE
Error: StarIO10UnsupportedModelError: Not supported model TSP650II/TSP654II [REQUEST]

### ISSUE THREAD

**Issue by manage-some** [star-micronics/react-native-star-io10#108]
It is mentioned in the docs that TSP650II is a supported model. I bought this model and and it shows TSP654II not supported when i try to connect. However TSP650II is actually TSP654II

I'm using LAN to connect

This is the printer model
![WhatsApp Image 2024-01-15 at 5 24 27 PM](https://github.com/star-micronics/react-native-star-io10/assets/113262320/49e1db55-5b27-4c67-a89c-b270e0fad3ba)

The Printer Model shows as this over ip
<img width="227" alt="Screenshot 2024-01-15 at 5 28 40 PM" src="https://github.com/star-micronics/react-native-star-io10/assets/113262320/ca83da64-4c1b-4cb3-a2e6-225da5b0d1f9">

It connects fine on windows driver and prints as well over lan. 
![WhatsApp Image 2024-01-15 at 5 31 57 PM](https://github.com/star-micronics/react-native-star-io10/assets/113262320/906aed26-6e37-4ca5-b814-a4384362a1dc)
![WhatsApp Image 2024-01-15 at 5 32 00 PM](https://github.com/star-micronics/react-native-star-io10/assets/113262320/21b179b2-1994-47bd-9a7c-956d37dc345e)

But on android/ios using this sdk i get this error on print. Discovery is fine though
<img width="556" alt="Screenshot 2024-01-15 at 5 26 07 PM" src="https://github.com/star-micronics/react-native-star-io10/assets/113262320/c91327cb-674a-46fe-86e9-78c1febfef35">

Any help would be appreciated

**Comment by YuzoKato** [comment]
Your printer is set to ESC/POS emulation. Please try StarLine mode by switching the dip switch 1-1 to ON. You can access the dip switch by opening the plate at the bottom. 
![スクリーンショット 2024-01-16 102333](https://github.com/star-micronics/react-native-star-io10/assets/72480753/d56f520a-44fd-49c0-ae9f-20da3446073d)
After changing the dip switch 1-1, you can see "StarLine" under "Dip Switch 1 Detail" in a test print in stead of "ESC/POS".

**Comment by manage-some** [comment]
> Your printer is set to ESC/POS emulation. Please try StarLine mode by switching the dip switch 1-1 to ON. You can access the dip switch by opening the plate at the bottom. ![スクリーンショット 2024-01-16 102333](https://private-user-images.githubusercontent.com/72480753/296905938-d56f520a-44fd-49c0-ae9f-20da3446073d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDI5MzAsIm5iZiI6MTcwNTQwMjYzMCwicGF0aCI6Ii83MjQ4MDc1My8yOTY5MDU5MzgtZDU2ZjUyMGEtNDRmZC00OWMwLWFlOWYtMjBkYTM0NDYwNzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEwNTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MzNhM2FmNDY3ZjI0Yjc1Mjk0MTY2NmNhMDJhNjQyYWJmMmNhYjE0ZGE5ZDQ1ZGMxYmE5OGQxZTcyZTM0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i4hMwN7ApDYOGwAncWFePsLSFrlX-JOb8pF18g9O4k0) After changing the dip switch 1-1, you can see "StarLine" under "Dip Switch 1 Detail" in a test print in stead of "ESC/POS".

Worked Flawlessly. Thank you for you help. Much appreciated. 🙏
