### ISSUE TITLE
Column support

### ISSUE THREAD

**Issue by mic7010** [star-micronics/react-native-star-io10#11]
Does the SDK support columns whereby I can print a barcode followed by a price for example. If so, example code would be appreciated

**Comment by bandit-ibayashi** [comment]
You can create a column if it uses horizontal tabs.
Define the tab position in advance with the [styleHorizontalTabPositions](https://www.star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-xpand-command/printer-builder/style-horizontal-tab-positions.html) method, and put the horizontal tab in the text.

```
var builder = new StarXpandCommand.StarXpandCommandBuilder();
builder.addDocument(new StarXpandCommand.DocumentBuilder()
    .addPrinter(new StarXpandCommand.PrinterBuilder()
        .styleAlignment(StarXpandCommand.Printer.Alignment.Center)
        .actionPrintBarcode(new StarXpandCommand.Printer.BarcodeParameter('0123456', StarXpandCommand.Printer.BarcodeSymbology.Jan8)
            .setBarDots(3)
            .setBarRatioLevel(StarXpandCommand.Printer.BarcodeBarRatioLevel.Level0)
            .setHeight(5)
            .setPrintHri(true)
        )
        .actionFeedLine(1)
        .styleAlignment(StarXpandCommand.Printer.Alignment.Left)
        .styleHorizontalTabPositions([12,37])
        .actionPrintText("SKU\tDescription\tTotal\n")
        .actionPrintText("------------------------------------------------")
        .actionPrintText("300678566\tPLAIN T-SHIRT\t10.99\n" + 
            "300692003\tBLACK DENIM\t29.99\n" + 
            "300651148\tBLUE DENIM\t29.99\n")
        .actionCut(StarXpandCommand.Printer.CutType.Partial)
    )
);
```

<img src="https://user-images.githubusercontent.com/60959945/120747620-4e760880-c53c-11eb-907a-cad026928e7a.jpg" width = "640px">

**Comment by mic7010** [comment]
What I meant was showing a barcode next to it a price. Can the SDK support the format below?

![image](https://user-images.githubusercontent.com/24941275/123542453-71b66100-d752-11eb-8680-e76d74129516.png)

**Comment by mic7010** [comment]
@bandit-ibayashi  - I am evaluating the Star printer and need to know if it will support the format above. Please answer either way.

**Comment by mic7010** [comment]
@bandit-ibayashi - any comments?

**Comment by gare-bear** [comment]
@mic7010 the text portion ( Nestile Drink mix.../ Tuna Yellowfin) is no problem.
But the printer cannot print a barcode and text side by side.

When printing barcodes, the next command/method always starts on the next line. For that reason, its not possible to print two different types of content side by side using `actionPrintBarcode()` and `actionPrintText()`

Instead create the content graphically and use `actionPrintImage()` to print it.
