### ISSUE TITLE
Two Colour Printing with SP700

### ISSUE THREAD

**Issue by blah-kohte** [star-micronics/react-native-star-io10#111]
## Description
I’ve thoroughly explored the StarXpand SDK and various online resources, but I haven’t discovered a straightforward method for achieving red font printing using the react-native-star-io10 library. Is it possible to print in red with this library?

## Your printer
- Model Names:
    *SP700 (w/ black/red ribbon)*

## Project config:
- "react-native-star-io10": "1.3.0"
- "react": "18.2.0"
- "react-native": "0.71.14",

**Comment by can-miki** [comment]
Printing in red on SP700 using this library can be achieved using the following methods:
> styleInvert(enable: boolean) ：
> [https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-xpand-command/printer-builder/style-invert.html](url)


It can also be achieved by sending raw commands using the printRawData method of the StarPrinter class.
> printRawData(data: Array<number>):
> [https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-printer/print-raw-data.html](url)
> Star Impact Printer Command Specifications:
> [https://starmicronics.com/support/developers/impact-dot-matrix-printer-command-specs/](url)
> ESC 4 :[Name] Specify white/black inversion and red color printing
> ESC 5 :[Name] Cancel white/black inversion/specify black color printing

Please consider one of the ways above.

**Comment by blah-kohte** [comment]
Thanks very much! Took me a while but I managed to figure out `styleInvert()`. Appreciate the additional information and response! 👌
