### ISSUE TITLE
what does this library accept as image or base64 ?

### ISSUE THREAD

**Issue by Billionjester** [star-micronics/react-native-star-io10#112]
## Description
A clear and concise description.
what does this library accept as an image or base64  what if have image URL of have something like pdf or HTML
How to achieve the printing process ?

## Your device where the bug occurs 
 - Device: 
    *e.g. iPhone 13*
 - OS:
    *e.g. iOS 15.0*
 - Browser: 
    *e.g. Safari*
 - Version
    *e.g. 22*

## Your printer
- Model Names:
    *e.g. mC-Print3*
- Firmware Version:
    *e.g. 3.5*
- Interface:
    *e.g. Ethernet*

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

## Additional context
Any other context about your topic.

**Comment by can-miki** [comment]
Image sources that can be specified as parameters for [ImageParameter(source: string)](https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/ja/api-reference/star-xpand-command/display/image-parameter/constructor.html) are image sources in PNG, JPEG format, etc.
Unfortunately, PDF and HTML cannot be specified as they are not image sources.

**Comment by can-miki** [comment]
@Billionjester 
Please make yourself useful. #74
