### ISSUE TITLE
Apple's App Stores requires new privacy permissions from the library in order to be submitted to App Store

### ISSUE THREAD

**Issue by Waleed065** [star-micronics/react-native-star-io10#113]
Recently I got this email from App Store suggesting to includes some additional privacy information.
I don't know whether this has to be included on the Library side or the client side. 
Either way it would be helpful to add guide about this in the documentation of this project

<img width="686" alt="Screenshot 2024-03-18 at 5 20 43 AM" src="https://github.com/star-micronics/react-native-star-io10/assets/65929645/6abb7a23-bc22-4ac9-913a-a7a5f230632b">

**Comment by Premshankar-Searce** [comment]
@can-miki any update for above issue?

**Comment by can-miki** [comment]
Thank you for contacting us.
We are currently investigating this issue. We will be releasing an update to address this issue.
We apologize for the inconvenience and appreciate your understanding.
We will keep you updated as we make progress.

**Comment by can-miki** [comment]
Thank you for your cooperation.
We have released the following versions that are compatible with Apple Privacy Manifest.
[StarXpand SDK for iOS v2.6.1](https://github.com/star-micronics/StarXpand-SDK-iOS)
[StarXpand SDK for ReactNative v1.6.1](https://github.com/star-micronics/react-native-star-io10)

We kindly ask for your confirmation.

**Comment by Waleed065** [comment]
@can-miki It's resolved ✅
