### ISSUE TITLE
Could not find :stario10:.

### ISSUE THREAD

**Issue by ashleyww93** [star-micronics/react-native-star-io10#114]
## Description
I am unable to build an android application, I get the following error:

> Configure project :react-native-star-io10
WARNING: Using flatDir should be avoided because it doesn't support any meta-data formats.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find :stario10:.
     Required by:
         project :app > project :react-native-star-io10
         
         
![image](https://github.com/star-micronics/react-native-star-io10/assets/3884418/f8ee7208-d990-4044-9d5e-7c2f42f818ad)

## Your device where the bug occurs 
N/A

## Your printer
N/A

## Your development environment
ProductName:            macOS
ProductVersion:         14.4.1
BuildVersion:           23E224

Also, the result of executing the command `npx react-native info`.

System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 17.43 GB / 64.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 21.7.3
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.10
    path: /usr/local/bin/yarn
  npm:
    version: 10.5.0
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "34"
    Build Tools:
      - 28.0.3
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 34.0.0
    System Images:
      - android-24 | Google APIs ARM 64 v8a
      - android-24 | Google Play Intel x86 Atom
      - android-31 | Google APIs ARM 64 v8a
      - android-31 | Google Play Intel x86 Atom_64
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11668458
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

## To Reproduce
Add the library to an android application, and try and build. See Gradle error

## Expected behavior
The application should build.

**Comment by mengheangrat** [comment]
Did you config this yet?

`allprojects {
    repositories {
        flatDir {
            dirs "$rootDir/../node_modules/react-native-star-io10/android/src/lib"
        }
    }
}`

**Comment by ashleyww93** [comment]
I have this working now. I have a pretty hectic week with in person events, but I’ll be sure to circle back and update this ticket with how it was resolved.

**Comment by can-miki** [comment]
Hello everyone,

We would like to express our gratitude for your cooperation and support with the issues. 
We take your feedback very seriously as it plays an important role in improving our products and services.

Could you share the latest status on any issues?
Your active feedback and support are indispensable in building a better community. 
We sincerely appreciate your time and consideration.
Best regards.

**Comment by web-stacked** [comment]
what was the solution for this issue? im experiencing the same thing and i believe its because the way my expo project is setup, i noticed it only works when i use a "bare workflow" environment any input will be appreciated

**Comment by can-miki** [comment]
@web-stacked @paulnolan7 

Maybe it will give you a clue to the solution, please check the following issue.
https://github.com/star-micronics/react-native-star-io10/issues/117

**Comment by paulnolan7** [comment]
Ahh, yes thank you @can-miki #117  is the solution to the problem.
NOTE: for other EAS users it is now complaining about the minSdk being 23 whereas it needs 28, but that is a EAS configuration issue and not a problem with react-native-star-io10. So we can probably close this issue.

**Comment by can-miki** [comment]
@paulnolan7 
Thank you for your confirmation.
This library is built with minSdkVersion = 28. I hope this is helpful.
https://github.com/star-micronics/react-native-star-io10/blob/master/example/android/build.gradle

**Comment by web-stacked** [comment]
My issue was that i was getting peer dependency errors when installing the npm project with an outdated project so i moved everything to a new project and it worked
