### ISSUE TITLE
App built with Xcode 16 cannot find or print to LAN printers from iOS 18 devices

### ISSUE THREAD

**Issue by bandit-ibayashi** [star-micronics/react-native-star-io10#124]
## Description
LAN printers cannot be found during searches and printing is not possible in any cases with the condition below.

||iOS 17 or earlier|iOS 18|
|--|--|--|
|Xcode 15 or earlier|Not occur.|Not occur.|
|Xcode 16|Not occur.|**Occur**|

## Root cause
Under investigation.
If this issue can be resolved on our side, we plan to release an updated version with the necessary fixes.

## Temporary Workaround
**Build with Xcode 15.**
According to Apple's requirements, it is possible to provide deliverables built with the previous environment until March 2025.
https://developer.apple.com/news/?id=utw4yhtp
*Starting April 2025, apps uploaded to App Store Connect must be built with SDKs for iOS 18, iPadOS 18, tvOS 18, visionOS 2, or watchOS 11.*

**Comment by bandit-ibayashi** [comment]
We plan to update `react-native-star-io10` in early November to address this issue.
Thank you for your patience.

**Comment by luizhfff** [comment]
> We plan to update `react-native-star-io10` in early November to address this issue. Thank you for your patience.

hey @bandit-ibayashi , would you be able to tell if the new version will be compatible with :
"react": "17.0.2",
"react-native": "0.68.6",

Thanks

**Comment by bandit-ibayashi** [comment]
We had released version [2.8.0](https://github.com/star-micronics/react-native-star-io10/releases/tag/1.8.0), which includes a fix for this issue. Thank you for your patience.

@luizhfff We decide which version to target based on the released version of React Native and the support of other modules we use internally.
We do not intentionally control that only certain versions will work, but we are afraid please understand that 0.68 is already officially archived as well, and if it does not work, it will be difficult to support.
