### ISSUE TITLE
Does this library supports react native integration with star - weight scale devices ?

### ISSUE THREAD

**Issue by naitik-erpbuddies** [star-micronics/react-native-star-io10#127]
Is the library only compatible with Star Micronics printers or it support weight scale integration as well with react native?

**Comment by can-miki** [comment]
This ReactNative library is for Star’s printers. 

We have the following scale SDK, but none for React Native.
https://github.com/star-micronics/StarMgsIO-SDK-iOS-Swift
https://github.com/star-micronics/StarMgsIO-SDK-Android-Java
Note:
- This Scale repository is for the US market only.
You should keep in mind the model and sales region of the corresponding scale.
- The connection to the Scale is not through a printer.

**Comment by naitik-erpbuddies** [comment]
@can-miki can i use it for Canada ?

**Comment by can-miki** [comment]
For now, the scale for Canada is [mG-T Series POS Scales](https://starmicronics.com/product/mg-t-series-pos-scales/).
We carry other scales for the US market (sales site: [Scales](https://starmicronics.com/ntep-certified-scales-precision-pos/)), but only the mG-T Series POS Scales have Measurement Canada Certified.

If you have any further questions about scales, please submit an issue in the following repository:
https://github.com/star-micronics/StarMgsIO-SDK-iOS-Swift
https://github.com/star-micronics/StarMgsIO-SDK-Android-Java
