### ISSUE TITLE
StarIO10ArgumentError  - _errorCode:0

### ISSUE THREAD

**Issue by mengheangrat** [star-micronics/react-native-star-io10#14]
import {
  InterfaceType,
  StarDeviceDiscoveryManager,
  StarDeviceDiscoveryManagerFactory,
} from 'react-native-star-io10'

// const manager = StarDeviceDiscoveryManager
export const discover = async () => {
  try {
    // Specify your printer interface types.
    manager = await StarDeviceDiscoveryManagerFactory.create([
      InterfaceType.Bluetooth,
      InterfaceType.BluetoothLE,
    ])

    // Set discovery time. (option)
    manager.discoveryTime = 10000

    // Callback for printer found.
    manager.onPrinterFound = (printer) => {
      console.tron.log('======> onPrinterFound', printer)
    }

    // Callback for discovery finished. (option)
    manager.onDiscoveryFinished = () => {
      console.tron.log(`Discovery finished.`)
    }

    // Start discovery.
    await manager.startDiscovery()

    // Stop discovery.
    // await manager.stopDiscovery()
  } catch (error) {
    // Error.
    console.tron.log('discover on error ', error)
  }
}

**Comment by smsagithub** [comment]
Could you please let me know more deatils as below...
- What kind of printer model ?
- How do you connecting to printer ?
- When did error ocurr ?

**Comment by mengheangrat** [comment]
It's an error on discovery method.

**Comment by smsagithub** [comment]
Noted with Thank so much for your integrate with Star Printer . 
If you have any question please contact us any time.

**Comment by vatsal-gadhiya-searce** [comment]
@mengheangrat How did you resolve? I am getting the same error when using example app.

**Comment by vatsal-gadhiya-searce** [comment]
@smsagithub Can you please help me how we can resolved this? We are getting same error with the example app.
