### ISSUE TITLE
Is there a method to open the cash drawer ?

### ISSUE THREAD

**Issue by piyasil** [star-micronics/react-native-star-io10#23]
I can only find the property of drawer status.

**Comment by piyasil** [comment]
Found it. https://www.star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-xpand-command/index.html

**Comment by phuongna-comartek** [comment]
@piyasil can you share the a code snippet for open the drawer, I tried many ways with the StarXandCompandBuilder and DrawerBuilder classes but no luck so far :(

**Comment by yuliya9** [comment]
@phuongna-comartek That's what worked for me:
`const settings = new StarConnectionSettings()
settings.interfaceType = InterfaceType.Usb
const builder = new StarXpandCommand.StarXpandCommandBuilder()
builder.addDocument(new StarXpandCommand.DocumentBuilder()
  .addDrawer(new StarXpandCommand.DrawerBuilder().actionOpen(new OpenParameter())))
const printer = new StarPrinter(settings)
const commands = await builder.getCommands()
await printer.open()
await printer.print(commands)
await printer?.close()
await printer?.dispose()`

**Comment by yuliya9** [comment]
@phuongna-comartek This works for me:
```
const settings = new StarConnectionSettings()
settings.interfaceType = InterfaceType.Usb
const builder = new StarXpandCommand.StarXpandCommandBuilder()
builder.addDocument(new StarXpandCommand.DocumentBuilder()
  .addDrawer(new StarXpandCommand.DrawerBuilder().actionOpen(new OpenParameter())))
const printer = new StarPrinter(settings)
const commands = await builder.getCommands()
await printer.open()
await printer.print(commands)
await printer?.close()
await printer?.dispose()
```
