### ISSUE TITLE
Thai character support ?

### ISSUE THREAD

**Issue by piyasil** [star-micronics/react-native-star-io10#24]
Is there any plan to support Thai character ? I find that there is a support of character encoding `CodePage` but
1. How to assign the CodePage number ?
2. The character encoding is not supported on printer I am using which is TSP650II.

I refer to this doc http://www.starmicronics.com/support/mannualfolder/linemode_cm_en.pdf
The code page is on page 3-4 in which there is support for Thai (n = 21, codepage 874)

**Comment by gare-bear** [comment]
@piyasil we're you able to get it working?

**Comment by piyasil** [comment]
Yes, it was the hardware/firmware issue and my local dealer had it fixed.
