### ISSUE TITLE
Intermittent Printer open fails with error code: 0

### ISSUE THREAD

**Issue by anshah** [star-micronics/react-native-star-io10#28]
Failure is happening when we call open on the printer: 

```
let printer = new StarPrinter(printerConfig.connectionSettings);
await printer.open();
```

The exception we get is below:

```
"error":"{\n  \"name\": \"v\"\n}",

"error":{"_errorCode":0,"name":"v","line":63,"column":331,"sourceURL":"index.android.bundle"
```

Initially Printer open and print works fine for some time and then it starts failing continuously with this error. If we reinstall it gets fixed.

**Comment by bandit-ibayashi** [comment]
We are sorry not to response for a long time.
If you continue to have this problem, please let our staff in your region know along with the model, interface, and device information from [this page](https://starmicronics.com/support/ContactDetail.aspx?id=2).

**Comment by Frankiz123** [comment]
@bandit-ibayashi  what is the solution of Invalid resource not printing

**Comment by Frankiz123** [comment]
@bandit-ibayashi  any solution?

**Comment by gare-bear** [comment]
@Frankiz123 error code: 0 means there is no error.
https://github.com/star-micronics/react-native-star-io10/blob/83ad5d7a4acd444a2fcc1db05d2d7ee9d001c3ad/src/StarIO10ErrorCode.ts

We'll need more information to debug the issue.
