### ISSUE TITLE
How get this library in my project

### ISSUE THREAD

**Issue by kmamtora** [star-micronics/react-native-star-io10#3]
How do i get this library in react native project

**Comment by gare-bear** [comment]
@kmamtora could you elaborate on your question? Are you looking for instructions on running the example projects?
Take a look at the [README](https://github.com/star-micronics/react-native-star-io10/blob/master/example/README.md).

**Comment by kmamtora** [comment]
@gare-bear where do i get this package react-native-star-io10 in https://www.npmjs.com/
and also i clone the app and did yarn install 

 D:\ReactNative\StarPrint\react-native-star-io10-master\example> yarn install
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/@react-native-community/cli-platform-ios/-/cli-platform-ios-5.0.1-alpha.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOSPC: no space left on device, write"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS D:\ReactNative\StarPrint\react-native-star-io10-master\example>

**Comment by bandit-ibayashi** [comment]
@kmamtora Thank you for letting us know the additional Information.
We are planning on uploading to npm when we officially release. Thank you for your patience.

The error "ENOSPC" seems to be caused by insufficient disk space.
So, could you make sure there is enough free disk space?

**Comment by bandit-ibayashi** [comment]
@kmamtora We now support downloading from npm for the official version. Thank you for waiting!
https://www.npmjs.com/package/react-native-star-io10

**Comment by kmamtora** [comment]
Hi @bandit-ibayashi, now i get this error  Unable to resolve module `react-native-star-io10` from `src/scenes/printjs`: react-native-star-io10 could not be found within the project.

**Comment by bandit-ibayashi** [comment]
@kmamtora Could you try to clear react-native cache?
I have searched for this error and it seems that clearing the cache may solve this issue.

**Comment by kmamtora** [comment]
thanks
