### ISSUE TITLE
Incomplete documentation - MFi requirements

### ISSUE THREAD

**Issue by sandylewisau** [star-micronics/react-native-star-io10#31]
The README for this project and the associated linked documentation does not make mention of the need to register to receive the MFi Product Plan ID that's required to be submitted with the Apple release process.

Can the README file be updated to reflect this requirement along with the link to register please? Not being aware of this requirement from the beginning has now resulted in our app release being delayed and having the requirement listed here will help others in the future.

https://www.star-m.jp/eng/contact/su03/inquiry03-4.html

**Comment by bandit-ibayashi** [comment]
We added this information on [ReadMe](
https://github.com/star-micronics/react-native-star-io10#4-apple-approval-process-for-star-mfi-applications).

We appreciate your suggestion.
