### ISSUE TITLE
[TSP100IIIBI] How much is the image width set

### ISSUE THREAD

**Issue by JoyJoyMe** [star-micronics/react-native-star-io10#33]
` .actionPrintImage(new StarXpandCommand.Printer.ImageParameter(uri, width))`

How do I know the width of the printed paper？

**Comment by gare-bear** [comment]
@JoyJoyMe the Xpand SDK doesn't expose the paper width, but the TSP100III has a pixel width of 576 dots.

**Comment by kickbk** [comment]
@gare-bear to be able to print an image 100%, we need to pass the pixel width of the printer we are printing on, right? and your SDK doesn't allow fetching the pixel width from the printer (odd, but ok...).
Perhaps one possible solution will be to fetch the model name (the SDK does expose that), and with a simple chart, get the pixel width of the model? If my logic is correct, could you please provide such a chart with all your models and their pixel widths so we can use it? Thanks!

**Comment by gare-bear** [comment]
@kickbk we're going to enable the wiki on this repo in the near future, so I will add the chart you requested there. 
For now, this issue has been answered and resolved.

**Comment by Dwikavindra** [comment]
Hi, is this wiki available yet? I got multiple printers to support one of them being mPop, do you happen to know what the print width is ? @gare-bear

**Comment by can-miki** [comment]
Please refer to [this wiki](https://github.com/star-micronics/StarPRNT-SDK-Android-Java/wiki/Number-of-dots-for-each-paper-width)
Please also refer to [this](https://www.star-m.jp/products/s_print/sdk/passprnt/manual/android/en/data_specifications.html#id44). 

We would like to improve the documentation based on everyone's opinions. 
Thank you for your cooperation.
