### ISSUE TITLE
Fresco 2.5.0

### ISSUE THREAD

**Issue by israelko** [star-micronics/react-native-star-io10#34]
Hello,

We are using Fresco 2.5.0 in our react native android app, and it seems to conflict with the code in your library and cause build errors regarding the following:

- **BaseBitmapDataSubscriber.onFailureImpl()** signature has changed (param should not be nullable anymore)

https://github.com/star-micronics/react-native-star-io10/blob/1392dff4d2992b30b70e6a051605f04a08c9fcc2/android/src/main/java/com/stario10module/StarIO10ValueConverter.kt#L680

- A newer version of OkHttpClient is used, so the **body()** method of the Response object is deprecated and was replace with the "**body**" property

https://github.com/star-micronics/react-native-star-io10/blob/1392dff4d2992b30b70e6a051605f04a08c9fcc2/android/src/main/java/com/stario10module/StarIO10ValueConverter.kt#L729

https://github.com/star-micronics/react-native-star-io10/blob/1392dff4d2992b30b70e6a051605f04a08c9fcc2/android/src/main/java/com/stario10module/StarIO10ValueConverter.kt#L731

Are you planing on supporting the newer versions of Fresco so the lib can be used in projects that use them?

Thanks!

**Comment by gare-bear** [comment]
@israelko is this the [Fresco](https://github.com/facebook/fresco) you're referring to?

**Comment by israelko** [comment]
@gare-bear yes

**Comment by JoyJoyMe** [comment]
When will this issue be solved? @gare-bear

**Comment by israelko** [comment]
Hi,
Any news regarding this issue?

Thanks!

**Comment by bandit-ibayashi** [comment]
Sorry for the delay in commenting.
It has changed to the `body` property in version 1.1.0, so I think it works fine now.

Thank you for your report!

**Comment by bandit-ibayashi** [comment]
A detailed description is answered below.
https://github.com/star-micronics/react-native-star-io10/issues/37#issuecomment-1075807803
