### ISSUE TITLE
manager.discoveryTime

### ISSUE THREAD

**Issue by kickbk** [star-micronics/react-native-star-io10#46]
Could you please explain why this delay is necessary? Are some devices of specific interfaces not picked up right away?

**Comment by bandit-ibayashi** [comment]
@kickbk [discoveryTime](https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-device-discovery-manager/discovery-time.html?highlight=discoverytime) means time to search for a device, not delay.
The device is searched for the milliseconds specified this.
