### ISSUE TITLE
Cannot discovery in Android

### ISSUE THREAD

**Issue by louistanntt** [star-micronics/react-native-star-io10#48]
In iOS I found 2 printers (TSP650II and mC_Print3) by Lan. But in Android, I could not find any devices.
Here is my problem: 
```
try {
      let manager = await StarDeviceDiscoveryManagerFactory.create(interfaceType);

      manager.discoveryTime = 10000;

      let newPrinters = [];

      manager.onPrinterFound = (printer) => {
        // iOS working well but Android does not
        newPrinters.push(printer);
        newPrinters = newPrinters.filter(
          (thing, index, self) =>
            index ===
            self.findIndex(
              (t) => t?.connectionSettings?.identifier === thing?.connectionSettings?.identifier,
            ),
        );
        setState({ ...state, printers: newPrinters });
        setStartFind(false);
      };

      manager.onDiscoveryFinished = () => {
        setStartFind(false);
      };

      await manager.startDiscovery();
    } catch (error) {
      setStartFind(false);
      alert(error);
    }
```
Any solution for this problem. Thank you!

**Comment by Frankiz123** [comment]
same problem any solution @louistanntt  ?

**Comment by jesperjohansson** [comment]
I have the same issue on Android emulator. Do you have the problem on a physical device?

**Comment by bandit-ibayashi** [comment]
As far as I have confirmed, I was able to search for LAN printers on Android using a Google Pixel 4a (Android 12).
If you continue to be unable to search on your actual Android device, please provide us with detailed information about your Android device.

**Comment by Frankiz123** [comment]
@bandit-ibayashi  why app is crash on andorid tablet or android phone when i click print but works fine on ios

**Comment by Frankiz123** [comment]
@bandit-ibayashi  i am using bluetooth for printing receipt

**Comment by gare-bear** [comment]
@Frankiz123 Unless you're having a problem with printer discovery, this isn't the right place to ask this question. Please open a new issue.

**Comment by Frankiz123** [comment]
yes @gare-bear

**Comment by Frankiz123** [comment]
ok @gare-bear  i will create a new ticket

**Comment by gare-bear** [comment]
@louistanntt are you still having this issue? Bandit tested and couldn't reproduce.

**Comment by bandit-ibayashi** [comment]
Since this Issue has not moved for a while and we have not been able to reproduce it here, we are closing it. If you continue to experience similar problems, please start a new Issue.
