### ISSUE TITLE
How to align printed image?

### ISSUE THREAD

**Issue by pedromcunha** [star-micronics/react-native-star-io10#5]
Hi, I'm trying to print an image on our receipt and it works well once I realized that the image can't be an SVG (should probably add to the docs). The only thing that I'm having trouble with now is placement of the image. How do I go about doing this? I'm using the `actionPrintImage` command. Thanks in advance.

**Comment by gare-bear** [comment]
@pedromcunha the simplest approach to this would be to make the image the full pixel width of the printer.
384px for 2" thermal printers
210px for 3" dot matrix printers
576px for 3" thermal printers
832px for 4" thermal printers
