### ISSUE TITLE
setting paper upside down

### ISSUE THREAD

**Issue by naotoisoda** [star-micronics/react-native-star-io10#52]
When I set paper upside down , the empty receipt is outputted. 
But, the program sees it as success and goes on to the 'then' process not 'catch'.
Is there some solutions to find error when I set paper upside down?
My printer is MCP31.

紙を上下逆（下から上に紙が来ている状態）でセットすると、真っ白な紙がパーシャルカットのみされて出力されます。
このとき、プログラム上は、印刷が成功したとみなしているようで、後続の処理を行ってしまいます。
これを防ぐために、紙の向きが逆の状態を判別する、もしくは、紙の向きが逆のときにエラーを表示する
などをすることはできないでしょうか？

**Comment by gare-bear** [comment]
@naotoisoda This is not really an issue with the React Native SDK, but to answer your question there is no way for the printer to detect if the paper is in the correct orientation. 

Some printers have a label on the inside of the paper cover with a diagram showing the correct way to insert the paper. 
Here's an example of this label on the MCP31
![IMG_20220317_183944_resized](https://user-images.githubusercontent.com/12755175/158909534-853ef3f4-96ea-4462-aab6-a79adc1cd93a.png)

**Comment by naotoisoda** [comment]
Thank you for your reply.
I understand that.
