### ISSUE TITLE
found printer but device not found action print

### ISSUE THREAD

**Issue by tuan2603** [star-micronics/react-native-star-io10#53]
Found printer:  {"_connectionSettings": {"autoSwitchInterface": false, "identifier": "00116206E180", "interfaceType": "Lan"}, "_displayDelegate": {"_onConnected": [Function anonymous], "_onDisconnected": [Function anonymous], "_onEventSet": [Function anonymous], "onCommunicationError": [Function anonymous]}, "_drawerDelegate": {"_onEventSet": [Function anonymous], "_onOpenCloseSignalSwitched": [Function anonymous], "onCommunicationError": [Function anonymous]}, "_eventSubscriptions": [{"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}, {"remove": [Function remove]}], "_information": {"_emulation": "StarGraphic", "_model": "Unknown", "_reserved": Map {"multiSession" => true, "responseVersion" => "1.0.1", "dhcp" => true, "usbSerialNumber" => null, "bluetoothAddress" => null, "productSerialNumber" => null, "configSubnetMask" => "0.0.0.0", "macAddress" => "00116206E180", "deviceModel" => "TSP143 (STR_T-001)", "ipAddressProtocol" => "DHCP", "configPrint" => null, "rarp" => null, "deviceCommandSet" => "STAR", "name" => "TSP100LAN", "specifiedIdentifier" => null, "deviceManufacturer" => "Star", "subnetMask" => "255.255.255.0", "hostName" => null, "configGateway" => "0.0.0.0", "nameDetail" => null, "usedIPAddress" => null, "firmwareVersionBoot" => "100", "deviceStatus" => null, "usedPort" => null, "firmwareVersionMain" => "200.110", "configIPAddress" => "0.0.0.0", "ipAddress" => "192.168.1.2", "gateway" => "192.168.1.1", "ipVersion" => 1, "pldRevision" => "", "deviceClass" => "PRINTER"}}, "_inputDeviceDelegate": {"_onConnected": [Function anonymous], "_onDataReceived": [Function anonymous], "_onDisconnected": [Function anonymous], "_onEventSet": [Function anonymous], "onCommunicationError": [Function anonymous]}, "_lock": {"_locked": false, "_sleep": [Function anonymous]}, "_printerDelegate": {"_onCoverClosed": [Function anonymous], "_onCoverOpened": [Function anonymous], "_onError": [Function anonymous], "_onEventSet": [Function anonymous], "_onPaperEmpty": [Function anonymous], "_onPaperNearEmpty": [Function anonymous], "_onPaperReady": [Function anonymous], "_onReady": [Function anonymous], "onCommunicationError": [Function anonymous]}, "getStatusTimeout": 5000, "openTimeout": 10000, "printTimeout": 30000}
 LOG  Found printer:  {"autoSwitchInterface": false, "identifier": "00116206E180", "interfaceType": "Lan"}
 LOG  Found printer: 00116206E180.
 LOG  Discovery finished.
 LOG  Error: StarIO10NotFoundError: Device not found.
 LOG  Error: StarIO10NotFoundError: Device not found.

Please support. thank so much!

**Comment by gare-bear** [comment]
Hi @tuan2603, unfortunately the TSP100LAN is not supported by this SDK. 
You can find a list of supported printers [here](https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/introduction/index.html#supported-model).
