### ISSUE TITLE
How to Use StarSdk Printer for android bluetooth not working

### ISSUE THREAD

**Issue by Frankiz123** [star-micronics/react-native-star-io10#60]
hi @gare-bear @Lozrus @bandit-ibayashi I am able to print successfully on ios using Bluetooth but I am not able to find discovery on android how can I print out using android using bluetooth can you elaborate

**Comment by Frankiz123** [comment]
@gare-bear  any update?

**Comment by Frankiz123** [comment]
@Isra1610 Sure heres the drive link you can download it and check it https://drive.google.com/file/d/1QECIsz4BDZ1-vjvA-4pTI_WttyMAeTpB/view?usp=sharing

**Comment by Frankiz123** [comment]
but it works on ios but android it was'nt working

**Comment by can-miki** [comment]
Sorry for late reply.
Please refer to our [README - 2. When using a Bluetooth printer](https://github.com/star-micronics/react-native-star-io10?tab=readme-ov-file#2-when-using-a-bluetooth-printer)

**Comment by can-miki** [comment]
We will close this issue once, but if the problem is still not resolved, please reopen it or post a new issue.
