### ISSUE TITLE
Star SDK discovered id on android but n

### ISSUE THREAD

**Issue by Frankiz123** [star-micronics/react-native-star-io10#61]
hi @gare-bear @Lozrus @bandit-ibayashi  I am attaching image can you explain why it did'nt print on android on ios its perfectly work fine

![WhatsApp Image 2022-05-14 at 12 01 45 AM](https://user-images.githubusercontent.com/17431855/168372608-41ae5d42-fbe5-4d99-8ff2-fd504055d49b.jpeg)

**Comment by gare-bear** [comment]
@Frankiz123 which Bluetooth printer do you have?

**Comment by Frankiz123** [comment]
@gare-bear  TSP100IIIBI

**Comment by Frankiz123** [comment]
@gare-bear  any update?
