### ISSUE TITLE
[BUG]I can't build an Android application in debugging

### ISSUE THREAD

**Issue by VladimirKraswov** [star-micronics/react-native-star-io10#64]
## I can't build an Android application in debugging

 - OS:
    Android

## The build crashes with this error
[Fatal Error] txw2-2.2.11.pom:7:3: The element type "hr" must be terminated by the matching end-tag "</hr>".
e: /Users/vladimirkrasov/work/Hermes-Operator-App/node_modules/react-native-star-io10/android/src/main/java/com/stario10module/StarIO10ValueConverter.kt: (711, 26): Cannot access 'body': it is package-private in 'Response'
e: /Users/vladimirkrasov/work/Hermes-Operator-App/node_modules/react-native-star-io10/android/src/main/java/com/stario10module/StarIO10ValueConverter.kt: (713, 30): Cannot access 'body': it is package-private in 'Response'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-star-io10:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by gare-bear** [comment]
@VladimirKraswov the issue ("cannot access body...")  has been discussed in issue #37 and is the result of a specification change in the okhttp package. Please take a look at the comment by [Bandit](https://github.com/star-micronics/react-native-star-io10/issues/37#issuecomment-1075807803).

**Comment by gare-bear** [comment]
@bandit-ibayashi Since this question has been asked a few times now, I think it would be valuable to add this to the Wiki.

**Comment by bandit-ibayashi** [comment]
@gare-bear I have uploaded this information on Wiki.
https://github.com/star-micronics/react-native-star-io10/wiki/FAQ#android-error-cannot-access-body-it-is-package-private-in-response
