### ISSUE TITLE
Is printing on multiple connected printers from one device supported?

### ISSUE THREAD

**Issue by fragilehm** [star-micronics/react-native-star-io10#65]
## Description

I have a case where multiple printers can be connected to one device, could be any interface. Say I have 5 printers connected, 2 Bluetooth, and 3 LAN printers to the same device, and I want to send a print command to all printers at the same time, will there be collisions? Do I have to disconnect from a printer before connecting and printing on another one, or should prints be done sequentially on each printer?

**Comment by fragilehm** [comment]
@gare-bear any idea?

**Comment by gare-bear** [comment]
hi @fragilehm,

I haven't tried that many printers at once, but it should work assuming you have 5 unique printer objects. 

It's worth mentioning when you open a connection to the printer using `printer.open()`,  the device holds that connection. 
Other devices won't be able to connect to the printer(s) until you release the connection with `printer.close()` 

I'd expect a one device scenario to work as expected, but additional devices will run into issues depending on how long you keep the printer connection active.

If your use-case requires that you share printers across multiple devices, then close the connection immediately after printing so other devices can print too. Expect errors, while attempting to connect to a printer that is in use.

**Comment by bandit-ibayashi** [comment]
This Issue is closed because it works for us and has not moved for a period of time.
