### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by veljko1992** [star-micronics/react-native-star-io10#66]
How can I set the font size on the TSP654II printer? I did it with style Magnification, but between 1 and 2 is a huge difference.

**Comment by gare-bear** [comment]
You can set the font using `styleFont(StarXpandCommand.Printer.FontType)`.
Then you can specify one of the printers built-in fonts; FontA or Font B.
Font A is the default, Font B is slightly smaller.

[Reference](https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-xpand-command/printer-builder/style-font.html#star-xpand-command-printer-builder-style-font)

**Comment by yongmin86k** [comment]
Is there a way to decrease the size than magnification 1 of FontB?

**Comment by gare-bear** [comment]
@yongmin86k unfortunately no. Font B is our smallest font, and 1x magnification is also the smallest. 
If those options are still too big, then you should create your receipts graphically, which would allow you to set the font & size at runtime.
