### ISSUE TITLE
Unable to search for devices and printers on latest android version.

### ISSUE THREAD

**Issue by hamzaahzam** [star-micronics/react-native-star-io10#67]
## Description
Unable to search for devices and printers on latest android version.

## Device where the bug occurs 
 - Device: 
    Samsung Galaxy A12, Redmi note 10 Pro
 - OS:
    Android 11,Android 12
 - Build by Android Studio chipmunk
 - Version of react-native:
 {
"react": "17.0.2",
"react-native": "0.68.2",
"react-native-star-io10": "^1.2.0",
}

## Your printer
- Model Names:
    *Portable Thermal Printer SM-L300*
- Firmware Version:
    SM-L300
- Interface:
    Bluetooth

## Your development environment
macOS

Also, the result of executing the command `npx react-native info`.

## Code To Reproduce
```
const discoverPrinters = async () => {
    try {
      var printersToSave = [];
      var printerList = [];
      var interfaceTypes = [
        Platform.OS === 'ios'
          ? InterfaceType.BluetoothLE
          : InterfaceType.Bluetooth,
      ];
      var manager = await StarDeviceDiscoveryManagerFactory.create(
        interfaceTypes,
      );

      manager.discoveryTime = 5000;

      // Callback for printer found.
      manager.onPrinterFound = printer => {
        printersToSave.push(printer);
        printerList.push({
          label: printer.connectionSettings.identifier,
          value: printer,
        });
        if (printer.connectionSettings.identifier === printerId) {
          // setSelectedPrinter(printer)
          setSelectedPrinter({
            label: printer.connectionSettings.identifier,
            value: printer,
          });
          dispatch(updatePrinter(printer));
        }
        // if()
      };

      manager.onDiscoveryFinished = () => {
        setPrinters(printerList);
      };
      await manager.startDiscovery();
    } catch (error) {}
  };
```

## Error
In android 12 while running the above code app crashes and in android 11 app doesn't crashes but unable to scan nearby printer.
But same code works fine on android 10 and earlier versions.

**Comment by bandit-ibayashi** [comment]
@hamzaahzam Could you please refer to the following URL and check if the permissions are properly granted according to the target SDK version?
https://github.com/star-micronics/react-native-star-io10#android

**Comment by DevHumzaAhzam** [comment]
@bandit-ibayashi I have added all the permissions for android it is only crashing on my Redmi Note 10 Pro android version 12

**Comment by DevHumzaAhzam** [comment]
In Logs I am getting this error 
`java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@655f4942: AdapterService getBondedDevices`

**Comment by mohsinmughal1630** [comment]
same issue i am facing

**Comment by bandit-ibayashi** [comment]
@hamzaahzam 

It is possible to request the permission `android.permission.BLUETOOTH_CONNECT` with the following code, but could you still not get the permission by doing this?
https://github.com/star-micronics/react-native-star-io10/blob/e544aacab74b480540558641dc8003a7126f30d8/example/samples/discovery/App.tsx#L101

This code must be executed when Android 12 or later and targetSDKVersion is 31 or later.

https://github.com/star-micronics/react-native-star-io10/blob/e544aacab74b480540558641dc8003a7126f30d8/example/samples/discovery/App.tsx#L38


I executed our Discovery sample code on a Google Pixel 6 with Android 12 and was able to successfully search for Bluetooth printers.

**Comment by Frankiz123** [comment]
@bandit-ibayashi I CAN discover the printer on my android device but the thing is when i try to print out it doesn't print any thing eventhough i have created 2 tickets on which @gare-bear  ask me about printer and i mentioned the printer but still no response can you tell me about the update does that works now or not?

**Comment by DevHumzaAhzam** [comment]
@bandit-ibayashi Thanks after requesting android permission I was able to find printers and send request for printing.

But I am facing an issue on Redmi Note 10 Pro after requesting permission it starts searching for printers but always returns nothing on **onDiscoveryFinished**

**Comment by bandit-ibayashi** [comment]
@DevHumzaAhzam 

Found printers are retrieved with [onPrinterFound](https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-device-discovery-manager/on-printer-found.html#star-device-discovery-manager-on-printer-found) property, not [onDiscoveryFinished](https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-device-discovery-manager/on-discovery-finished.html).
`onDiscoveryFinished` property indicates that it only notifies the user that the Discovery process is finished and does not return information on the printers found as a result of the Discovery process.
You can also refer the [sample code](https://github.com/star-micronics/react-native-star-io10/blob/e544aacab74b480540558641dc8003a7126f30d8/example/samples/discovery/App.tsx#L73) here.

Or would it be a case where `onDiscoveryFinished` is issued as soon as [startDiscovery](https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-device-discovery-manager/start-discovery.html#star-device-discovery-manager-start-discovery) method is executed in your situation with Redmi Note 10 Pro?

**Comment by bandit-ibayashi** [comment]
We will close it once there have been no comments for a certain period of time.
If you continue to experience this problem, please create a new Issue.
