### ISSUE TITLE
 Direct local .aar file dependencies are not supported when building an AAR. 

### ISSUE THREAD

**Issue by tuan2603** [star-micronics/react-native-star-io10#69]
> Task :react-native-star-io10:bundleReleaseLocalLintAar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-star-io10:bundleReleaseLocalLintAar'.
> Error while evaluating property 'hasLocalAarDeps' of task ':react-native-star-io10:bundleReleaseLocalLintAar'
   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-star-io10 project caused this error: /Users/abc/apps/nameproject/node_modules/react-native-star-io10/android/src/lib/stario10.aar

android/build.gradle
 ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
        kotlinVersion = "1.6.10"
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
         classpath('com.android.tools.build:gradle:7.2.1')
         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

- package.json
    "react": "17.0.2",
    "react-native": "0.67.2",
"react-native-star-io10": "^1.2.0",

thank. Please help me!

**Comment by kfernandes29** [comment]
Same issue here. Anyone know to correct this?

**Comment by bandit-ibayashi** [comment]
There are same issues https://github.com/star-micronics/react-native-star-io10/issues/29 and https://github.com/star-micronics/react-native-star-io10/issues/51, and we are very pleased with the suggestions on how to correct this  https://github.com/star-micronics/react-native-star-io10/pull/56 .
