### ISSUE TITLE
[BUG] apk size is huge

### ISSUE THREAD

**Issue by vivekvardhanadepu** [star-micronics/react-native-star-io10#75]
example apk size is ~90MB, which is huge for a printer pkg. Is it possible to shrink it somehow?

**Comment by bandit-ibayashi** [comment]
@vivekvardhanadepu The sample SDK is provided solely to demonstrate API usage and behavior, and is not primarily focused on optimization.

To actually build and use your app, please consider using the App Bundle as described in the Official Android Developer's Guide below.
https://developer.android.com/topic/performance/reduce-apk-size
