### ISSUE TITLE
[BUG] - Unable to find any printers using USB in IOS

### ISSUE THREAD

**Issue by JattCoder** [star-micronics/react-native-star-io10#76]
## Description
I used code directly from docs for testing. It doesn't find any printers. The printer is connected to Square USB Hub and powered on. 

## Your device where the bug occurs 
 - Device: 
    Square Terminal with Ipad pro
 - OS:
    iOS 15.6.1
 - Browser: 
    N/A
 - Version
    N/A

## Your printer
- Model Names:
    Star - TSP100lll
- Firmware Version:
   N/A
- Interface:
    USB

## To Reproduce
Steps to reproduce the behaviour:
Created TS file and used code from docs.

Permissions:
        <key>UISupportedExternalAccessoryProtocols</key>
	<string>jp.star-m.starpro</string>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>[DESC]</string>
	<key>NSLocalNetworkUsageDescription</key>
	<string>[DESC]</string>

**Comment by bandit-ibayashi** [comment]
@JattCoder Sorry for our late reply.
Just to be sure first, please confirm on the front operation panel that your printer is TSP100IIIU.
Some other TSP100III models have a USB-A port, but that is for power supply and cannot be used for iPad communication.
![image](https://user-images.githubusercontent.com/60959945/207509270-4e65ab1d-2c4e-42fa-995d-64093904b87c.png)

Next, if possible, install our Star Quick Setup Utility on your iPad Pro with the current connection configuration and try to search for the printer.
https://apps.apple.com/us/app/star-quick-setup-utility/id1549088652

**Comment by gare-bear** [comment]
@JattCoder any update? were you able to fix your issue?
