### ISSUE TITLE
Unable to print Japanese Text on SM-L300

### ISSUE THREAD

**Issue by DevHumzaAhzam** [star-micronics/react-native-star-io10#79]
## Description
I am trying to print a Japanese string but instead it leaves a blank space

## Your device where the bug occurs 
 - Device: 
    *iPhone 13*
 - OS:
    *iOS 15.0*

## Your printer
- Model Names:
    *SM-L300*
- Interface:
    *Bluetooth*

**Comment by DevHumzaAhzam** [comment]
@bandit-ibayashi I have a major release in Japan at the end of this week can you please help me out with this issue ?
I have even tried this 
`styleInternationalCharacter(StarXpandCommand.Printer.InternationalCharacterType.Usa)`
but still unable to print Japanese string.

**Comment by amjadislam** [comment]
I'm Facing the same issue, can anyone help?

**Comment by DevHumzaAhzam** [comment]
@bandit-ibayashi my bad I didn't know that I have to update the printer settings. After updating Japanese is printing.
Thank you.
