### ISSUE TITLE
Scanning bluetooth with IOS 

### ISSUE THREAD

**Issue by kmamtora** [star-micronics/react-native-star-io10#8]
I have scanning bluetooth printers code that works well for android but for ios it doesnt give any error nor it finds bluetooth devices here is my code
`
    try {
      await this._manager?.stopDiscovery();

      var interfaceTypes = [];

      interfaceTypes.push(InterfaceType.Bluetooth);

      this._manager = await StarDeviceDiscoveryManagerFactory.create(
        interfaceTypes,
      );
      this._manager.discoveryTime = 10000;

      this._manager.onPrinterFound = (printer) => {
        const printers = this.state.printers;
    

        console.log(`Found printer: ${printer.connectionSettings.identifier}.`);
      };

      this._manager.onDiscoveryFinished = async () => {
        console.log(`Discovery finished.`);
        
      };

      await this._manager.startDiscovery();
    } catch (error) {
      console.log(`Error: ${String(error)}`);
    }
`

**Comment by gare-bear** [comment]
@kmamtora after the npm install, theres a few steps that must be done in Xcode which are documented [here](https://github.com/star-micronics/react-native-star-io10#ios). Can you confirm you've done that?

**Comment by kmamtora** [comment]
@gare-bear Yes I have already executed this this steps 

![Screen Shot 2021-04-16 at 10 39 30 AM](https://user-images.githubusercontent.com/44718980/114974544-34a33800-9ea0-11eb-926e-14c508a64e30.png)

**Comment by kmamtora** [comment]
Any update on this ?

**Comment by gare-bear** [comment]
@kmamtora i'm looking into it. Can you tell me which printer you're targeting? 
iOS has different Bluetooth requirements than Android; mainly products must be paired and MFi certified, so if you're not paired or using a product that is not MFi certified it could it could impede your ability to discover it.

**Comment by kmamtora** [comment]
mPop, TSP100 and MCP31C BK US, this are the models which I have and have tried with mPop which is not working

**Comment by gare-bear** [comment]
@kmamtora iOS has a strict 1-1 pairing requirement, any chance the printer is paired with another device?
I also suggest testing the printer with our [mPOP utility](https://apps.apple.com/us/app/mpop-utility/id993563930) and see if its detected.

Seems more like a connectivity issue than a code issue.

**Comment by gare-bear** [comment]
@kmamtora we're you able to resolve this issue?

**Comment by dillondrobena** [comment]
Also having a similar issue with an mPop drawer/printer combo. The mPop utility discovers it fine, but not my code. If I connect directly to the printer through bluetooth the code scanning picks it up, otherwise it doesn't show anything

**Comment by gare-bear** [comment]
@dillondrobena You have to pair the printer prior to use, this SDK won't be able to discover it otherwise. 
The mPOP Utility is not a react native app, it is a native Swift app using our [StarPRNT SDK for iOS](https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift). 
The APIs are different and the StarPRNT SDK can discover nearby Bluetooth printers, even when not connected.
