### ISSUE TITLE
Is this repo maintained/monitored? No responses for months

### ISSUE THREAD

**Issue by joarwilk** [star-micronics/react-native-star-io10#82]
These printers are mission-critical to our operations. If this repo is not maintained we need to be aware of it so we can direct our questions elsewhere.

We spend tens of thousands of dollars on printers per quarter - we expect more than this.

**Comment by bandit-ibayashi** [comment]
@joarwilk and to all those who agree with this Issue

We deeply apologize that we have not been able to meet your expectations regarding our response to Issue.
We will review our response to improve this operation and thank you for your continued efforts.

**Comment by joarwilk** [comment]
@can-miki Did you get a notification or something? I haven't looked at this issue for over a year but today I opened it just by chance and ten minutes later you close it. Was this a _crazy_ coincidence or did something else happen?

**Comment by can-miki** [comment]
@joarwilk 
I'm sorry for surprising you.
We are currently working hard to resolve issues on GitHub. Therefore, we close inquiries that have been answered for one year.
Things will get better, but if the issue is still not resolved, please reopen it or post a new issue.
Thank you for contacting us.

**Comment by joarwilk** [comment]
You did not surprise me and everything is OK. But I'm too curious - was this just by chance? That I happened to visit the issue right before you closed it?

**Comment by can-miki** [comment]
It could be a miracle!
We will continue to diligently monitor the repository. 
We will do our best to provide better solutions, and we look forward to your continued patronage.

**Comment by joarwilk** [comment]
That is WILD haha. Alright thanks.
