### ISSUE TITLE
I want to know BLE Characteristic details.

### ISSUE THREAD

**Issue by narita-takeru** [star-micronics/react-native-star-io10#88]
## Description

Without using sdk, are the characteristic details of ble published?

## Your printer
- Model Names:
    SM-L200
- Interface:
    Bluetooth BLE

**Comment by nagai-smjp** [comment]
We are happy for try to use SM-L200.
But I'm afraid to say,UUID Spec of SM-L200 is not published.
So I'd like to communcate by E-Mail already you sent us.

By the way,I think this is not reated react native SDK.
Could you please close this issue?
Thanks,
Nagai.

**Comment by gare-bear** [comment]
@narita-takeru @nagai-smjp I'll close this issue since this discussion is not related to the SDK.
