### ISSUE TITLE
Flutter Support

### ISSUE THREAD

**Issue by ekokurniadi** [star-micronics/react-native-star-io10#89]
## Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
*I have a flutter desktop windows application with some printing feature, but i have some problem to use star mpop printer on my application.*

## Describe the solution you'd like
I hope star-micronic has support sdk for flutter not only react-native

**Comment by gare-bear** [comment]
@ekokurniadi we do not have an "official" flutter plugin but I know of this one by [ovatu](https://github.com/ovatu/starxpand_flutter).

**Comment by ekokurniadi** [comment]
@gare-bear thank you, but i need support for desktop windows

**Comment by gare-bear** [comment]
@gare-bear its still worth a look. Our SDK supports Windows so their wrapper could probably support Windows systems with very minimal work.

**Comment by ekokurniadi** [comment]
i'am so confuse, flutter desktop windows  is using c++ as native, but already sdk only support for c# specially uwp desktop,

**Comment by can-miki** [comment]
@ekokurniadi 
Thank you for your valuable request.
However, unfortunately, we do not have an "official" Flutter plugin currently.
If you use unofficial plugins, please test them thoroughly.
