### ISSUE TITLE
How to connect with USB printers?

### ISSUE THREAD

**Issue by smalik02** [star-micronics/react-native-star-io10#92]
## Description
I have been able to use the library to discover Bluetooth & WiFi/Lan printers. However, I was wondering how the usb connections would work if an app is running on tablet. Does it require additional hardware to interface with the USB connection? Can it communicate through the Square stand?

**Comment by Tatsuki-Yamamoto2731** [comment]
@smalik02 You don't need additional hardware to use USB printer. 

To answer your question more correctly, could you please provide the following information?

- What printer model do you use? 
- If possible, could you please upload the self-printing result?
   - Self-printing can be performed by turning on the printer while pressing the FEED button.

Regarding printer models supported by Square, please refer to the links below.
https://squareup.com/us/en/compatibility/accessories/receipt-printers?country_redirection=true

**Comment by smalik02** [comment]
I would be looking at supporting the TSP100IIIU (USB version of the TSP100III). 

I don't have the self printing for that printer on hand, but I can get one at a later stage. My question is - how would the tablet pick up the USB printer? I see that there is a `Supported external accessory protocols` key that you have to use.

**Comment by gare-bear** [comment]
@smalik02 Because the TSP100III is an Apple MFi certified product, and we use the External Accessory interface to interface with it. Our library wraps some parts of the External Accessory framework and by specificying that your app supports Star's  accessory protocol, you can access the printer.

**Comment by smalik02** [comment]
Awesome - that makes sense.
