### ISSUE TITLE
kotlin-gradle-plugin version required by package not recent enough for react-native 0.73.0

### ISSUE THREAD

**Issue by smilank3** [star-micronics/react-native-star-io10#93]
## development environment
macOS - M1

## What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-star-io10' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10

**Comment by gare-bear** [comment]
@smilank3 Could you take a look at our bug report template and provide all the information we require?
We want to help you but we need all that information in order to do so.

**Comment by gare-bear** [comment]
@smilank3 glad you fixed your issue! Mind sharing your fix?

**Comment by smilank3** [comment]
@gare-bear run-ios works fine but android still shows an error.

info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-star-io10' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10

**Comment by gare-bear** [comment]
@smilank3 ok we'll look into the Android build issues

**Comment by smilank3** [comment]
@gare-bear Any progress? i  am trying to publish my app (android). run-ios works fine.

# Here is the detail error log.
warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
info JS server already running.
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-star-io10' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-star-io10' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
 

# My package.json
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/checkbox": "^0.5.14",
    "@react-native-picker/picker": "^2.4.8",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.7",
    "crypto-js": "^4.1.1",
    "date-fns": "^2.29.3",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "react-native-qrcode-svg": "^6.2.0",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-sound": "^0.11.2",
    "react-native-star-io10": "^1.2.0",
    "react-native-svg": "^13.8.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-view-shot": "^3.5.0",
    "react-responsive-modal": "^6.4.1",
    "socket.io": "^2.4.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.7",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by gare-bear** [comment]
@smilank3 still working on it. need more time.

**Comment by smilank3** [comment]
@gare-bear  did you manage to solve the issue?

**Comment by smilank3** [comment]
@gare-bear latest version v1.3.0 works fine.
