### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by mengheangrat** [star-micronics/react-native-star-io10#99]
"react": "18.2.0",
 "react-native": "0.71.4",
 "react-native-star-io10": "^1.3.0"

**Comment by bandit-ibayashi** [comment]
@mengheangrat Could you please fill in the Issue Template and provide the required information?

**Comment by mengheangrat** [comment]
This error happen when I build into devices. if I build with simulator is ok.
